In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
from __future__ import absolute_import, division, print_function
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Flatten, Reshape
from keras.layers import Convolution2D, MaxPooling2D
from keras.utils import np_utils
import pickle
from matplotlib import pyplot as plt
import seaborn as sns

In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [6]:
from google.colab import drive
drive.mount('/content/drive') 

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
data = pd.read_csv('/content/drive/My Drive/8dec/project/Churn.csv')

In [35]:
data

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [0]:
#2. Drop the columns which are unique for all users like IDs (2.5 points)


In [0]:
X = data.iloc[:, 3:13].values

In [0]:
y = data.iloc[:, 13].values

In [0]:
#Distinguish the feature and target set (2.5 points)

In [10]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [0]:
labelencoder_X_1 = LabelEncoder()

In [0]:
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [0]:
labelencoder_X_2 = LabelEncoder()

In [0]:
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [17]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
#4. Divide the data set into train and test sets

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
#Now let’s make the ANN

In [0]:
import keras
from keras.models import Sequential

In [0]:
from keras.layers import Dense

In [0]:
#6. Initialize & build the model (10 points)
#Initializing the ANN…
So there are actually 2 ways of initializing a deep learning model
— — — 1)Defining each layer one by one
— — — 2)Defining a Graph
We did not put any parameter in the Sequential object as we will be defining the Layers manually

In [23]:
classifier = Sequential()

In [0]:
#Adding the input layer and the first hidden layer…
#Here avg= (11+1)/2==>6 So set Output Dim=6
#Init will initialize the Hidden Layer weights uniformly
#Activation Function is Rectifier Activation Function(Relu)

In [24]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [25]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [26]:
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
#Compiling the ANN

In [27]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [28]:
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.




Epoch 1/100





8000/8000 [==============================] - 2s 227us/step - loss: 0.4853 - acc: 0.7956
Epoch 2/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4290 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.4232 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4184 - acc: 0.8154
Epoch 5/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4155 - acc: 0.8259
Epoch 6/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4137 - acc: 0.8305
Epoch 7/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4120 - acc: 0.8325
Epoch 8/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4106 - acc: 0.8326
Epoch 9/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4101 - acc: 0.8334
Epoch 10/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4089 - acc:

In [0]:
# Predict the results using 0.5 as a threshold (5 points)

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [30]:
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [0]:
#10. Print the Accuracy score and confusion matrix (2.5 points)

In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1503   92]
 [ 200  205]]
