### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [1]:
!pip install -U tensorflow==2.0 --quiet

     |████████████████████████████████| 86.3MB 26kB/s 
     |████████████████████████████████| 450kB 22.5MB/s 
     |████████████████████████████████| 3.8MB 32.4MB/s 
     |████████████████████████████████| 81kB 7.9MB/s 
ERROR: tensorboard 2.0.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.7.2 which is incompatible.


In [0]:
import tensorflow as tf

In [3]:
tf.__version__

'2.0.0'

#### Collect Fashion mnist data from tf.keras.datasets 

In [4]:
import keras

Using TensorFlow backend.


In [5]:
(trainX, trainY), (testX, testY) = keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 1s 0us/step


#### Change train and test labels into one-hot vectors

In [0]:
trainY = tf.keras.utils.to_categorical(trainY, num_classes=10)
testY = tf.keras.utils.to_categorical(testY, num_classes=10)

In [7]:
testY[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [8]:
print(trainY.shape)
print('First 5 examples now are: ', trainY[0:5])

(60000, 10)
First 5 examples now are:  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Build the Graph

#### Initialize model, reshape & normalize data

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784 2D amtrix converted to 1D matrix 
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalize the data - getting numbers between 0 to 1 
model.add(tf.keras.layers.BatchNormalization())

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [0]:
#Hidden layers
model.add(tf.keras.layers.Dense(200, activation='relu', name='Layer_1'))
model.add(tf.keras.layers.Dense(100, activation='relu', name='Layer_2'))
#Dropout layer
model.add(tf.keras.layers.Dropout(0.25))

### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [0]:
#Output layer
model.add(tf.keras.layers.Dense(10, activation='softmax', name='Output'))

In [0]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape (Reshape)            (None, 784)               0         
_________________________________________________________________
batch_normalization (BatchNo (None, 784)               3136      
_________________________________________________________________
Layer_1 (Dense)              (None, 200)               157000    
_________________________________________________________________
Layer_2 (Dense)              (None, 100)               20100     
_________________________________________________________________
dropout (Dropout)            (None, 100)               0         
_________________________________________________________________
Output (Dense)               (None, 10)                1010      
Total params: 181,246
Trainable params: 179,678
Non-trainable params: 1,568
______________________________________________

In [14]:
#Train the model
model.fit(trainX,trainY,
          validation_data=(testX,testY),
          epochs=40,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/40
60000/60000 [==============================] - 13s 219us/sample - loss: 0.5141 - accuracy: 0.8168 - val_loss: 0.4307 - val_accuracy: 0.8443
Epoch 2/40
60000/60000 [==============================] - 13s 217us/sample - loss: 0.3966 - accuracy: 0.8561 - val_loss: 0.3799 - val_accuracy: 0.8590
Epoch 3/40
60000/60000 [==============================] - 10s 175us/sample - loss: 0.3612 - accuracy: 0.8667 - val_loss: 0.3767 - val_accuracy: 0.8693
Epoch 4/40
60000/60000 [==============================] - 11s 189us/sample - loss: 0.3349 - accuracy: 0.8773 - val_loss: 0.3570 - val_accuracy: 0.8740
Epoch 5/40
60000/60000 [==============================] - 11s 186us/sample - loss: 0.3157 - accuracy: 0.8830 - val_loss: 0.3879 - val_accuracy: 0.8666
Epoch 6/40
60000/60000 [==============================] - 12s 203us/sample - loss: 0.3022 - accuracy: 0.8880 - val_loss: 0.3816 - val_accuracy: 0.8755
Epoch 7/40
60000/60000 [====================

In [0]:
model.save('dnn_1.h5')

In [0]:
model = tf.keras.models.load_model('dnn_1.h5')